sudo: false
language: php
php:
    - '7.0.8'
before_script:
    - composer self-update
    - composer install
script:
    - chmod -R 777 tests/logs
    - ./vendor/bin/phpunit --coverage-clover tests/logs/clover.xml
    - chmod 777 tests/logs/clover.xml
after_success:
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then travis_retry php vendor/bin/coveralls; fi
